### ISSUE TITLE
是不是可以再添加一个可以直接script标签直接引用的文件

### ISSUE THREAD

**Issue by MrXhh** [weihongyu12/chinese-idcard-checker#2]
我们一些旧项目就可以直接引用使用，新项目可以使用这种的

**Comment by weihongyu12** [comment]
@MrXhh 直接使用`<script>`标签可以直接引用unpkg

- https://unpkg.com/chinese-idcard-checker@1.0.3/dist/IDCardChecker.js
- https://unpkg.com/chinese-idcard-checker@1.0.3/dist/IDCardChecker.min.js
